server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: nickz
    password: password
    url: jdbc:postgresql://postgres:5432/notification
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  zipkin:
    base-url: http://zipkin:9411

  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
        defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true


rabbitmq:
  exchanges:
      internal: internal.exchange
  queue:
      notification: notification.queue
  routing-keys:
      internal-notification: internal.notification.routing-key